### ISSUE TITLE
Doesn't compile on macOS 11.4 (Intel i5 CPU), Xcode 13.1, Swift 5.5

### ISSUE THREAD

**Issue by mkll** [LuizZak/SwiftRewriter#58]
```
~/Development/macOS/SwiftRewriter$ swift run -c=release SwiftRewriter path ./objc/ 
remark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with who/Users/mkII/Development/macOS/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:120:46: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
    let textSize = hasCustomText ? Int(cnode.range.length) : 0
                                       ~~~~~ ^~~~~
/Users/mkII/Development/macOS/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:153:35: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
      let startOffset = Int(cnode.range.offset)
                            ~~~~~ ^~~~~
/Users/mkII/Development/macOS/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:157:55: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
      let end = utf8.index(begin, offsetBy: Int(cnode.range.length))
                                                ~~~~~ ^~~~~
/Users/mkII/Development/macOS/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:873:32: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
    let byteLength = Int(cnode.range.length)
                         ~~~~~ ^~~~~
/Users/mkII/Development/macOS/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntax/SyntaxParser.swift:195:57: error: missing argument for parameter #3 in call
    let c_top = swiftparse_parse_string(c_parser, source)
                                                        ^
                                                        , <#Int#>
_InternalSwiftSyntaxParser.swiftparse_parse_string:1:13: note: 'swiftparse_parse_string' declared here
public func swiftparse_parse_string(_: swiftparse_parser_t!, _ source: UnsafePointer<CChar>!, _ len: Int) -> swiftparse_client_node_t!
            ^
[2/4] Compiling SwiftSyntax AbsolutePosition.swift
error: fatalError
```

**Comment by LuizZak** [comment]
Can you try the `swift5.5` branch and see if it compiles?

**Comment by mkll** [comment]
Oh, I didn't notice that such a branch exists, my bad. I'll try in a minute.

**Comment by mkll** [comment]
@LuizZak Yes, it compiles, thanks!
