### ISSUE TITLE
execute 'swift build' faile

### ISSUE THREAD

**Issue by lcztt** [LuizZak/SwiftRewriter#67]
SwiftRewriter git:(master) ✗ swift build
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/luochao/Desktop/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/CNodes.swift:13:29: error: no such module '_InternalSwiftSyntaxParser'
@_implementationOnly import _InternalSwiftSyntaxParser
                            ^
/Users/luochao/Desktop/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/CNodes.swift:13:29: error: no such module '_InternalSwiftSyntaxParser'
@_implementationOnly import _InternalSwiftSyntaxParser
                            ^
/Users/luochao/Desktop/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/CNodes.swift:13:29: error: no such module '_InternalSwiftSyntaxParser'
@_implementationOnly import _InternalSwiftSyntaxParser
                            ^
/Users/luochao/Desktop/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/CNodes.swift:13:29: error: no such module '_InternalSwiftSyntaxParser'
@_implementationOnly import _InternalSwiftSyntaxParser
                            ^
/Users/luochao/Desktop/SwiftRewriter/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/CNodes.swift:13:29: error: no such module '_InternalSwiftSyntaxParser'
@_implementationOnly import _InternalSwiftSyntaxParser
                            ^
[8/101] Compiling SwiftFormatCore RuleBasedFindingCategory.swift

mac os version:13.1 (22C65)
Xcode version:Version 14.3.1 (14E300c)
SwiftRewriter Version: master branch and latest version

**Comment by LuizZak** [comment]
Hi! It seems to be a mismatch between the SwiftSyntax version used as a dependency and the one installed on the system. I'll check that out and push a branch that should work with Xcode 14.3.1.

**Comment by LuizZak** [comment]
Hi, could you try the [`swift-5.8`](https://github.com/LuizZak/SwiftRewriter/tree/swift-5.8) branch and see if it works?

**Comment by lcztt** [comment]
Thank you for providing the solution. I used the code from the 'swift-5.8' branch and successfully executed the 'swift build' command. You were a great help to me.
